
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: prueba2_christian_development

test:
  <<: *default
  database: prueba2_christian_test

production:
  <<: *default
  database: prueba2_christian_production
  username: examen1
  password: <%= ENV['EXAMEN1_DATABASE_PASSWORD'] %>
